# Generated by Django 2.2.5 on 2021-04-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20210420_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
